### ISSUE TITLE
Cache is being rebuilt after rollback

### ISSUE THREAD

**Issue by kuzux** [athal7/thermos#22]
If we are updating a model in a transaction. Say, the update is performed, saved to DB, but then the DB transaction is rolled back, thermos still regenerates the cache even if the transaction is rolled back. 

In most use cases, the cache regeneration block would perform a db query and would not be receiving the changed data from the DB. So, that operation would not result in a cache entry with invalid data being generated, but only a small performance hit

**Comment by athal7** [comment]
Thanks @kuzux! This has been included in the latest release:
https://rubygems.org/gems/thermos/versions/0.3.0
