### ISSUE TITLE
Model Concern/Class Method

### ISSUE THREAD

**Issue by julianrubisch** [athal7/thermos#37]
Hi!

I came across this gem while looking up possible names on rubygems.org 😅

And I thought: awesome! A Rails cache warming gem that is up to date and not abandoned, but...

Maybe I don't get the overall intent, but what I am looking for is an even simpler API that would allow me to refresh model partial fragment caches upon changes.

Some model concern that could simply be included, optionally register which partials/views are dependent on it and refresh the cache fragments for them.

```ruby
class Post < ApplicationRecord
  include Thermos...

  keep_warm_for "posts/_post", "users/_posts"

  ...
end
```

Would something like this be doable with Thermos?

**Comment by athal7** [comment]
Hi @julianrubisch, thanks for reaching out. I think it would be possible to implement something like that, but I'm not sure the benefit would be large.  since you would still need to go to the database to fetch the model to pass into the fragment cache. Especially in cases of Russian Doll caching, you would still be making larger DB calls, which in my experience are a larger contributor to performance issues than rendering/serialization.

Are you running into a case where the rendering is more of a bottleneck than the db calls? Or just hoping to have a simpler API to avoid re-tooling your fragment cache definitions?

**Comment by julianrubisch** [comment]
That's right, I'm simply thinking in terms of DX and/or conceptual compression here.

I'd like to give any team of developers the ability to experience an improvement with the lowest barrier possible.

**Comment by julianrubisch** [comment]
This is not to say that this should be part of Thermos at any cost. I was just wondering if that would strike a chord with you.

**Comment by athal7** [comment]
Totally makes sense. I do think what you're suggesting would be a DX improvement, I'm just not sure whether it would be a significant performance boost, and would lose many of the more powerful thermos features (e.g. dependency mappings for cache). 

What do you think about something in between... namely making `Thermos.fill` and `Thermos.keep_warm` available in the view context so they can be an in-place swap for the calls to `cache`?

**Comment by athal7** [comment]
Actually I'm going to see what I can do to spike on your idea, maybe I can add those dependency definitions in the `keep_warm_for` or something along those lines. Going to be getting potentially into some private Rails APIs, but worth a shot even if it doesn't generate the level of performance gains of the primary way of using.

**Comment by julianrubisch** [comment]
Maybe I'm a bit lost here, but why would warming cache fragments for records and/or collections of them not result in a performance boost?

**Comment by athal7** [comment]
It would, I just don't know how significant of a boost it would be because the db lookups still have to happen in order to have the object in hand to pass into the call to `cache` in your example. Vs the other ways of using Thermos completely avoid db lookups and use request parameters for the cache lookup. 

But I see what you're in saying that it's still an improvement for avoiding cache misses for existing fragments, even if the benefit isn't anywhere near as large as the full Thermos implementation.

**Comment by julianrubisch** [comment]
Yes!

I'm looking for a drop-in mostly that would help even cache-inexperienced teams.

Also I very much value low level caching but it introduces a significant amount of complexity into an application that might not be welcomed by every dev lead etc.

Thank you for being open about this! Very much appreciated.

**Comment by julianrubisch** [comment]
Also you're right that with Russian doll caching most is to be gained with collections, which could present a significant implementation effort in your lib.

Still I would start small with individual partials.

**Comment by athal7** [comment]
I'll see what I can do.

I'm curious when you say "low level caching" what you're referring to. Just want to make sure the usage docs aren't misleading you to anything more complex than wrapping your `render` call in the relevant controller.

**Comment by julianrubisch** [comment]
I'll try it out for sure!

Disclosure, I'm writing this in my vacation without any access to a computer 😅 

So please, don't feel pressed or rushed.

**Comment by athal7** [comment]
👌🏻 I'll wait to hear back about how you find implementing Thermos as is (happy to do some pairing if desired) before spiking on this new idea. Typically it's a fairly simple wrapping of some of your controller code, and you don't necessarily need to replace/remove any of the other fragment caches that exist.

Hope you enjoy your vacation.

**Comment by julianrubisch** [comment]
Sure! Regarding this, I'm just a bit worried about duplication. But that could maybe also be alleviated by a controller concern maybe?

**Comment by athal7** [comment]
Duplication as in you are reusing the same partial in multiple controllers and you only want it taking up one key of space in your cache store? Keep in mind if you have Russian Doll caching, you incur these same costs of duplication. Just think of Thermos as adding an outer layer of cache.

**Comment by julianrubisch** [comment]
Yep, I get that. The thing is I'm not only rendering from controllers. So the best entity to define the cache, in my case, is in fact the model itself.

**Comment by athal7** [comment]
Oh... may I ask where you are rendering from? Anywhere where it would be infeasible to add Thermos to wrap your `render` call?

**Comment by julianrubisch** [comment]
Reflexes and jobs basically.

All feasible, but prone to duplication if you don't pay attention 😄

**Comment by athal7** [comment]
Got it. You should be able to use the fill/drink strategy to squash that duplication
